export default [
    {
        id:1,
        name : "Motorola G32",
        price : "11,999",
        originalPrice : "18,999",
        discount: 36,
        category : "electronic",
        subCategory : "mobile",
        RAM : 8,
        ROM : 128,
        battery : 5000,
        processor : "Qualcomm Snapdragon 680 Processor",
        frontCamera : 16,
        backCamera : 50,
        rating: 4.4,
        srcLink:"sdjf"
    },
    {
        id:2,
        name : "Poco C50",
        price : "5,749",
        originalPrice : "8,999",
        discount: 36,
        category : "electronic",
        subCategory : "mobile",
        RAM : 2,
        ROM : 32,
        battery : 5000,
        processor : "Mediatek Helio A22 Processor, Upto 2.0 GHz Processor",
        frontCamera : 5,
        backCamera : 8,
        rating: 4.0,
        srcLink:"sdjf"
    },
    {
        id:3,
        name : "Apple Iphone 14",
        price : "70,999",
        originalPrice : "79,999",
        discount: 11,
        category : "electronic",
        subCategory : "mobile",
        RAM : 6,
        ROM : 128,
        battery : 5000,
        processor : "A15 Bionic Chip, 6 Core Processor",
        frontCamera : 12,
        backCamera : 12,
        rating: 4.7,
        srcLink:"sdjf"
    },

    {
        id:4,
        name : "Apple Iphone 11",
        price : "40,999",
        originalPrice : "43,900",
        discount: 6,
        category : "electronic",
        subCategory : "mobile",
        RAM : 4,
        ROM : 64,
        battery : 5000,
        processor : "A13 Bionic Chip Processor",
        frontCamera : 12,
        backCamera : 12,
        rating: 4.6,
        srcLink:"sdjf"
    },
    {
        id:5,
        name : "Samsung Galaxy S32",
        price : "1,24,999",
        originalPrice : "1,49,999",
        discount: 16,
        category : "electronic",
        subCategory : "mobile",
        RAM : 12,
        ROM : 256,
        battery : 5000,
        processor : "Mediatek Helio P55 Processor",
        frontCamera : 12,
        backCamera : 200,
        rating: 4.0,
        srcLink:"sdjf"
    },
    {
        id:6,
        name : "Samsung Galaxy F04",
        price : "7,499",
        originalPrice : "11,499",
        discount: 34,
        category : "electronic",
        subCategory : "mobile",
        RAM : 4,
        ROM : 64,
        battery : 5000,
        processor : "Mediatek Helio P35 Processor",
        frontCamera : 5,
        backCamera : 13,
        rating: 4.5,
        srcLink:"sdjf"
    },
    {
        id:7,
        name : "Samsung Galaxy M33 5G",
        price : "16,348",
        originalPrice : "24,999",
        discount: 34,
        category : "electronic",
        subCategory : "mobile",
        RAM : 6,
        ROM : 128,
        battery : 5000,
        processor : "Mediatek Helio P35 Processor",
        frontCamera : 5,
        backCamera : 50,
        rating: 4.2,
        srcLink:"sdjf"
    },
]